version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: 
            name: Restore all dependencies
            command: dotnet restore      
      - run: 
            name: Build all projects
            command: dotnet build
      - run: 
            name: Run tests
            command: $(Get-ChildItem -Filter *.Tests) | %{ dotnet test --no-build --blame $_.Name }